#redirect: "http://localhost:8000/exporter/callback"
redirect: "https://teams-log-exporter.herokuapp.com/exporter/callback"
scopes: "openid profile offline_access user.read calendars.read onlinemeetings.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"